version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    volumes:
      - ./meili_data:/meili_data
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "thisdataisnotforallviewerskeepawayfromit"
    restart: always
